// SPEC-040 share-extension drop-in for Android.
//
// Drop this into the Tauri Mobile Android project (generated by
// `cargo tauri android init`) at:
//   mobile/gen/android/app/src/main/kotlin/io/anuna/zetl/mobile/share/
//
// Register it as an exported activity with an ACTION_SEND
// intent-filter in AndroidManifest.xml so the Android system surfaces
// zetl-mobile in the share sheet for text/plain content. After the
// activity appends the payload to the inbox file, it launches the
// main activity so the Tauri shell can pick it up on next start.
//
// The inbox path matches what the Rust side
// (`mobile_state::share_inbox_path`) computes: app_data_dir is the
// app's internal files dir on Android (Context.getFilesDir()), so
// the inbox lives at `<filesDir>/share-inbox.jsonl`.

package io.anuna.zetl.mobile.share

import android.app.Activity
import android.content.Intent
import android.os.Bundle
import org.json.JSONObject
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.TimeZone

class ShareReceiverActivity : Activity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        handleShareIntent(intent)
        relaunchMainActivity()
        finish()
    }

    private fun handleShareIntent(intent: Intent?) {
        if (intent?.action != Intent.ACTION_SEND) return
        val type = intent.type ?: return
        if (!type.startsWith("text/")) return

        val title = intent.getStringExtra(Intent.EXTRA_SUBJECT).orEmpty()
        val body = intent.getStringExtra(Intent.EXTRA_TEXT).orEmpty()
        val kind = when {
            body.startsWith("http://") || body.startsWith("https://") -> {
                if (title.isNotBlank()) "url_with_title" else "url"
            }
            else -> "text"
        }

        appendInboxEntry(kind, title, body)
    }

    private fun appendInboxEntry(kind: String, title: String, body: String) {
        val inbox = File(filesDir, "share-inbox.jsonl")
        val fmt = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", Locale.US).apply {
            timeZone = TimeZone.getTimeZone("UTC")
        }
        val entry = JSONObject().apply {
            put("received_at", fmt.format(Date()))
            put("kind", kind)
            put("title", title)
            put("body", body)
        }
        inbox.appendText(entry.toString() + "\n")
    }

    private fun relaunchMainActivity() {
        val launch = packageManager.getLaunchIntentForPackage(packageName)
            ?: return
        launch.flags = Intent.FLAG_ACTIVITY_NEW_TASK or
            Intent.FLAG_ACTIVITY_CLEAR_TOP or
            Intent.FLAG_ACTIVITY_SINGLE_TOP
        startActivity(launch)
    }
}
